[workspace]
members = ["atprotolib-rs"]
resolver = "2"

package.authors = [
    "Tim Small"
]
package.homepage = "https://github.com/Smalls1652/atprotolib-rs"
package.repository = "https://github.com/Smalls1652/atprotolib-rs"

package.license-file = "LICENSE"
